### ISSUE TITLE
create python file

### ISSUE THREAD

**Issue by emammadli052** [emammadli052/gcprepo#4]
Bir python code yazmaq lazimdi "Hello World" print etsin

**Comment by emammadli38** [comment]
Tamam yaradiram indi

**Comment by emammadli38** [comment]
he gozluyurem tez ol biraz

**Comment by emammadli052** [comment]
tama gozluyurem tez ol biraz

**Comment by emammadli38** [comment]
yoxla zehmet olmasa

**Comment by emammadli052** [comment]
ejdahasan cox sagol

**Comment by emammadli38** [comment]
cfbdfbgfb
