### ISSUE TITLE
bir problem var

### ISSUE THREAD

**Issue by emammadli052** [emammadli052/gcprepo#5]

**Comment by emammadli38** [comment]
nedi problem?

**Comment by emammadli052** [comment]
bir fayl duzelt hansiki orda 10 defe automatik olaraq Hello World yazsin

**Comment by emammadli38** [comment]
cover elememishem hemin movzunu ama calisharam edem

**Comment by emammadli052** [comment]
tamam celd ol

**Comment by emammadli38** [comment]
ok

**Comment by emammadli38** [comment]
fayl yaradildi ve problem hell olundu

**Comment by emammadli052** [comment]
cox sagol case bagalndi
